import type { RegionConfig } from './types';

/** 묵호(강원 동해시) 서비스 지역 설정 */
export const mukhoRegion: RegionConfig = {
  code: 'mukho',
  name: '묵호',
  tagline: '동해 바다와 함께하는 동행 · 공동구매',
  bannerTitle: '묵호에서 함께할 사람을 찾아요',
  bannerSubtitle: '묵호항 · 논골담길 · 묵호등대 주변 2km',
  mapCenter: { lat: 37.559, lng: 129.116 },
  searchRadiusKm: 2,
  spots: [
    { id: 'port', name: '묵호항', lat: 37.559, lng: 129.116 },
    { id: 'nongol', name: '논골담길', lat: 37.5585, lng: 129.114 },
    { id: 'lighthouse', name: '묵호등대', lat: 37.5578, lng: 129.1189 },
    { id: 'beach', name: '망상해변', lat: 37.565, lng: 129.125 },
  ],
  companions: [
    {
      id: 'c1',
      name: '지우',
      age: 26,
      category: 'meal',
      avatar: '/avatar-1.png',
      temperature: 68.4,
      distanceKm: 0.4,
      area: '묵호항',
      headline: '항구 회센터 같이 가실 분!',
      bio: '바다 내음과 함께하는 식사 동행을 좋아해요. 신선한 해산물 맛집 탐방 중입니다.',
      tags: ['해산물', '회', '묵호항'],
      lat: 37.5594,
      lng: 129.1152,
      matches: 42,
      responseRate: 96,
    },
    {
      id: 'c2',
      name: '도현',
      age: 29,
      category: 'exercise',
      avatar: '/avatar-2.png',
      temperature: 52.1,
      distanceKm: 1.2,
      area: '망상해변',
      headline: '아침 해변 러닝 메이트 구해요',
      bio: '주 3회 해변 러닝합니다. 일출 보며 가볍게 뛰고 싶은 분 환영!',
      tags: ['러닝', '해변', '일출'],
      lat: 37.5642,
      lng: 129.123,
      matches: 31,
      responseRate: 88,
    },
    {
      id: 'c3',
      name: '하늘',
      age: 24,
      category: 'travel',
      avatar: '/avatar-3.png',
      temperature: 74.9,
      distanceKm: 0.8,
      area: '논골담길',
      headline: '이번 주말 묵호 골목 투어 ✈️',
      bio: '사진 찍으며 골목길 산책하는 걸 좋아해요. 논골담길 카페 투어 같이해요!',
      tags: ['골목투어', '카페', '사진'],
      lat: 37.5588,
      lng: 129.1145,
      matches: 57,
      responseRate: 99,
    },
    {
      id: 'c4',
      name: '준서',
      age: 27,
      category: 'exercise',
      avatar: '/avatar-4.png',
      temperature: 45.6,
      distanceKm: 2.1,
      area: '동해역',
      headline: '주말 등대 코스 걷기 한 자리',
      bio: '묵호등대까지 해안 산책로를 걷는 걸 좋아합니다. 가벼운 페이스로 걸어요.',
      tags: ['등대', '트레킹', '해안'],
      lat: 37.5565,
      lng: 129.1195,
      matches: 23,
      responseRate: 81,
    },
    {
      id: 'c5',
      name: '서연',
      age: 28,
      category: 'meal',
      avatar: '/avatar-5.png',
      temperature: 61.2,
      distanceKm: 1.6,
      area: '묵호등대',
      headline: '혼밥 말고 같이 점심 어때요?',
      bio: '등대 근처 맛집 탐방 중이에요. 현지인 추천 메뉴 함께 드실 분 찾아요!',
      tags: ['현지맛집', '점심', '등대'],
      lat: 37.5575,
      lng: 129.118,
      matches: 38,
      responseRate: 92,
    },
    {
      id: 'c6',
      name: '민재',
      age: 25,
      category: 'travel',
      avatar: '/avatar-2.png',
      temperature: 39.8,
      distanceKm: 3,
      area: '묵호역',
      headline: '다음 달 강릉·속초 당일치기 🇰🇷',
      bio: '동해안 드라이브 동행 구합니다. 렌트카 나눠 타고 즐겁게 다녀요.',
      tags: ['당일치기', '드라이브', '동해안'],
      lat: 37.561,
      lng: 129.11,
      matches: 19,
      responseRate: 77,
    },
  ],
  products: [
    {
      id: 'a47bc3f0-cbe8-4664-86f8-cc88c81f3804',
      region: 'mukho',
      name: '묵호항 싱싱 회센터 세트',
      description: '당일 입항 대구·광어 회 2~3인분 + 해물탕. 묵호항에서 바로 픽업.',
      imageUrl: '/product-pt.png',
      sellerName: '묵호수산',
      category: 'food',
      ticketLabel: '2~3인분',
      regularPrice: 96000,
      discountRate: 0.4,
      targetCount: 4,
      currentCount: 1,
      groupBuyStatus: 'open',
    },
    {
      id: 'ca84cb14-564e-445b-98b4-b439db7f6a55',
      region: 'mukho',
      name: '논골담길·묵호등대 가이드 투어',
      description: '현지 가이드와 함께하는 3시간 도보 투어. 논골담길 + 묵호등대 코스.',
      imageUrl: '/product-pt.png',
      sellerName: '묵호로컬',
      category: 'tour',
      ticketLabel: '1인',
      regularPrice: 52000,
      discountRate: 0.35,
      targetCount: 6,
      currentCount: 3,
      groupBuyStatus: 'open',
    },
    {
      id: '703c8a96-2322-4cf6-bd5d-c7846f7b2f7a',
      region: 'mukho',
      name: '동해 특산품 선물세트',
      description: '오징어채·멸치젓·망고빙수 재료 등 묵호·동해 특산품 모음. 택배 발송.',
      imageUrl: '/product-pt.png',
      sellerName: '동해장터',
      category: 'gift',
      ticketLabel: '1세트',
      regularPrice: 48000,
      discountRate: 0.5,
      targetCount: 5,
      currentCount: 5,
      groupBuyStatus: 'success',
    },
  ],
};
